package DoubleLinkedListApp;


/**
* DoubleLinkedListApp/DoubleLinkedListOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DoubleLinkedList.idl
* Quinta-feira, 5 de Novembro de 2015 15h07min05s BRST
*/

public interface DoubleLinkedListOperations 
{
  boolean add (DoubleLinkedListApp.Pessoa pessoa);
  void addPosition (int posicao, DoubleLinkedListApp.Pessoa pessoa);
  DoubleLinkedListApp.Pessoa get (int posicao);
  DoubleLinkedListApp.Pessoa remove (int posicao);
  void shutdown ();
} // interface DoubleLinkedListOperations
