package DoubleLinkedListApp;

/**
* DoubleLinkedListApp/DoubleLinkedListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DoubleLinkedList.idl
* Quinta-feira, 5 de Novembro de 2015 15h07min05s BRST
*/

public final class DoubleLinkedListHolder implements org.omg.CORBA.portable.Streamable
{
  public DoubleLinkedListApp.DoubleLinkedList value = null;

  public DoubleLinkedListHolder ()
  {
  }

  public DoubleLinkedListHolder (DoubleLinkedListApp.DoubleLinkedList initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DoubleLinkedListApp.DoubleLinkedListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DoubleLinkedListApp.DoubleLinkedListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DoubleLinkedListApp.DoubleLinkedListHelper.type ();
  }

}
