package DoubleLinkedListApp;


/**
* DoubleLinkedListApp/DoubleLinkedList.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DoubleLinkedList.idl
* Quinta-feira, 5 de Novembro de 2015 15h07min05s BRST
*/

public interface DoubleLinkedList extends DoubleLinkedListOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DoubleLinkedList
