package DoubleLinkedListApp;


/**
* DoubleLinkedListApp/DoubleLinkedListPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DoubleLinkedList.idl
* Quinta-feira, 5 de Novembro de 2015 15h07min05s BRST
*/

public abstract class DoubleLinkedListPOA extends org.omg.PortableServer.Servant
 implements DoubleLinkedListApp.DoubleLinkedListOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("add", new java.lang.Integer (0));
    _methods.put ("addPosition", new java.lang.Integer (1));
    _methods.put ("get", new java.lang.Integer (2));
    _methods.put ("remove", new java.lang.Integer (3));
    _methods.put ("shutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DoubleLinkedListApp/DoubleLinkedList/add
       {
         DoubleLinkedListApp.Pessoa pessoa = DoubleLinkedListApp.PessoaHelper.read (in);
         boolean $result = false;
         $result = this.add (pessoa);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // DoubleLinkedListApp/DoubleLinkedList/addPosition
       {
         int posicao = in.read_long ();
         DoubleLinkedListApp.Pessoa pessoa = DoubleLinkedListApp.PessoaHelper.read (in);
         this.addPosition (posicao, pessoa);
         out = $rh.createReply();
         break;
       }

       case 2:  // DoubleLinkedListApp/DoubleLinkedList/get
       {
         int posicao = in.read_long ();
         DoubleLinkedListApp.Pessoa $result = null;
         $result = this.get (posicao);
         out = $rh.createReply();
         DoubleLinkedListApp.PessoaHelper.write (out, $result);
         break;
       }

       case 3:  // DoubleLinkedListApp/DoubleLinkedList/remove
       {
         int posicao = in.read_long ();
         DoubleLinkedListApp.Pessoa $result = null;
         $result = this.remove (posicao);
         out = $rh.createReply();
         DoubleLinkedListApp.PessoaHelper.write (out, $result);
         break;
       }

       case 4:  // DoubleLinkedListApp/DoubleLinkedList/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DoubleLinkedListApp/DoubleLinkedList:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DoubleLinkedList _this() 
  {
    return DoubleLinkedListHelper.narrow(
    super._this_object());
  }

  public DoubleLinkedList _this(org.omg.CORBA.ORB orb) 
  {
    return DoubleLinkedListHelper.narrow(
    super._this_object(orb));
  }


} // class DoubleLinkedListPOA
