package DoubleLinkedListApp;


/**
* DoubleLinkedListApp/DoubleLinkedListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DoubleLinkedList.idl
* Quinta-feira, 5 de Novembro de 2015 15h07min05s BRST
*/

abstract public class DoubleLinkedListHelper
{
  private static String  _id = "IDL:DoubleLinkedListApp/DoubleLinkedList:1.0";

  public static void insert (org.omg.CORBA.Any a, DoubleLinkedListApp.DoubleLinkedList that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DoubleLinkedListApp.DoubleLinkedList extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DoubleLinkedListApp.DoubleLinkedListHelper.id (), "DoubleLinkedList");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DoubleLinkedListApp.DoubleLinkedList read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DoubleLinkedListStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DoubleLinkedListApp.DoubleLinkedList value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DoubleLinkedListApp.DoubleLinkedList narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DoubleLinkedListApp.DoubleLinkedList)
      return (DoubleLinkedListApp.DoubleLinkedList)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DoubleLinkedListApp._DoubleLinkedListStub stub = new DoubleLinkedListApp._DoubleLinkedListStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DoubleLinkedListApp.DoubleLinkedList unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DoubleLinkedListApp.DoubleLinkedList)
      return (DoubleLinkedListApp.DoubleLinkedList)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DoubleLinkedListApp._DoubleLinkedListStub stub = new DoubleLinkedListApp._DoubleLinkedListStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
