package DoubleLinkedListApp;


/**
* DoubleLinkedListApp/Pessoa.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DoubleLinkedList.idl
* Quinta-feira, 5 de Novembro de 2015 15h07min05s BRST
*/

public final class Pessoa implements org.omg.CORBA.portable.IDLEntity
{
  public String nome = null;
  public int idade = (int)0;

  public Pessoa ()
  {
  } // ctor

  public Pessoa (String _nome, int _idade)
  {
    nome = _nome;
    idade = _idade;
  } // ctor

} // class Pessoa
