package DoubleLinkedListApp;

/**
* DoubleLinkedListApp/PessoaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DoubleLinkedList.idl
* Quinta-feira, 5 de Novembro de 2015 15h07min05s BRST
*/

public final class PessoaHolder implements org.omg.CORBA.portable.Streamable
{
  public DoubleLinkedListApp.Pessoa value = null;

  public PessoaHolder ()
  {
  }

  public PessoaHolder (DoubleLinkedListApp.Pessoa initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DoubleLinkedListApp.PessoaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DoubleLinkedListApp.PessoaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DoubleLinkedListApp.PessoaHelper.type ();
  }

}
